### ISSUE TITLE
WorkflowTemplate doesn't accept scope parameter

### ISSUE THREAD

**Issue by fxdgear** [opencdk8s/cdk8s-argoworkflow#10]
I'm trying to recreate this workflowtemplate: 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: workflow-template-submittable
spec:
  arguments:
    parameters:
      - name: message
        value: hello world
  templates:
    - name: whalesay-template
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay
        command: [cowsay]
        args: ["{{inputs.parameters.message}}"]
```
using this project. 

When I create my main.py module with: 

```python
#!/usr/bin/env python
from constructs import Construct
from cdk8s import App, Chart

from cdk8s_argoworkflow_resources import (
    WorkflowTemplate,
    WorkflowTemplateSpec,
    Arguments,
    Template,
    Inputs,
    Parameter,
)
from cdk8s_argoworkflow_resources.k8s import ObjectMeta, Container


class MyChart(Chart):
    def __init__(self, scope: Construct, id: str):
        super().__init__(scope, id)
        WorkflowTemplate(
            scope,
            api_version="argoproj.io/v1alpha1",
            kind="WorkflowTemplate",
            metadata=ObjectMeta(name="workflow-template-submittable"),
            spec=WorkflowTemplateSpec(
                arguments=[
                    Arguments(parameters=Parameter(name="message", value="hello world"))
                ],
                templates=[
                    Template(
                        name="whalesay-template",
                        inputs=Inputs(parameters="message"),
                        container=Container(
                            name="whalesay",
                            image="docker/whalesay",
                            command=["cowsay"],
                            args=["{{inputs.parameters.message}}"],
                        ),
                    )
                ],
            ),
        )


app = App()
MyChart(app, "workflow-template-submittable")
app.synth()
```

I get the following error: 

```
TypeError: WorkflowTemplate.__init__() takes 1 positional argument but 2 positional arguments (and 4 keyword-only arguments) were given
```

When I look at the resources created in python I can see that scope is not an option for `WorkflowTemplate` but there is another object called `ArgoWorkflowClusterWorkflowTemplate` which does accept scope. 

At this point I only want to create a workfow template, not a cluster workflow template. 

is this an error or am I doing things wrong?
